// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkyjr3bPAPbqLeH2M3k_WhiM8MVXwjzc',
    appId: '1:854926758913:web:5927b29d0d5f4f62e71c00',
    messagingSenderId: '854926758913',
    projectId: 'purr-purr-pad-d28bb',
    authDomain: 'purr-purr-pad-d28bb.firebaseapp.com',
    storageBucket: 'purr-purr-pad-d28bb.firebasestorage.app',
    measurementId: 'G-GJWKR3PTDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjRuhrD84-1CbUGUj5W97yqnc1i9MxYpI',
    appId: '1:854926758913:android:64e3c45029f79cede71c00',
    messagingSenderId: '854926758913',
    projectId: 'purr-purr-pad-d28bb',
    storageBucket: 'purr-purr-pad-d28bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5L3EjKy9gxmGn-mlVl0MFzqiuK3nj0s',
    appId: '1:854926758913:ios:24904b0957823b63e71c00',
    messagingSenderId: '854926758913',
    projectId: 'purr-purr-pad-d28bb',
    storageBucket: 'purr-purr-pad-d28bb.firebasestorage.app',
    iosBundleId: 'com.example.myMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu5L3EjKy9gxmGn-mlVl0MFzqiuK3nj0s',
    appId: '1:854926758913:ios:24904b0957823b63e71c00',
    messagingSenderId: '854926758913',
    projectId: 'purr-purr-pad-d28bb',
    storageBucket: 'purr-purr-pad-d28bb.firebasestorage.app',
    iosBundleId: 'com.example.myMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNkyjr3bPAPbqLeH2M3k_WhiM8MVXwjzc',
    appId: '1:854926758913:web:f388188a39056f2ae71c00',
    messagingSenderId: '854926758913',
    projectId: 'purr-purr-pad-d28bb',
    authDomain: 'purr-purr-pad-d28bb.firebaseapp.com',
    storageBucket: 'purr-purr-pad-d28bb.firebasestorage.app',
    measurementId: 'G-N72VGES46D',
  );
}
